-- 124_role_module_matrix.sql
-- Role-wise MODULE access for the whole HRMS, from Khushal's Role-Access sheet
-- (EZER-Role-Access-Final.html SEED), aggregated from leaf screens to module level.
-- Idempotent. Sets access for the 13 system roles across 24 modules; the 3 modules
-- not in the sheet (Database Export, Company Dashboard, ESS Reports) are left as-is,
-- and ALL_ACCESS / ADMIN_SUPER / custom roles are untouched.
-- Levels: VIEW=read/approve, EDIT=create/edit, FULL=configure. Enforcement is on,
-- so this is what each role sees in ESS.

insert into public.role_permissions (role_id, module, access_level)
select r.id, v.module, v.access_level
from (values
  ('CFO', "Recruitment", 'VIEW'),
  ('CFO', "Onboarding", 'NONE'),
  ('CFO', "Performance", 'VIEW'),
  ('CFO', "Employees", 'VIEW'),
  ('CFO', "Bulk Upload", 'NONE'),
  ('CFO', "Transfer", 'NONE'),
  ('CFO', "Attendance", 'NONE'),
  ('CFO', "Attendance Reports", 'NONE'),
  ('CFO', "Leave Config", 'NONE'),
  ('CFO', "Holidays", 'NONE'),
  ('CFO', "Payroll", 'VIEW'),
  ('CFO', "Finance", 'VIEW'),
  ('CFO', "Flexi Claims", 'NONE'),
  ('CFO', "Travel Claims", 'VIEW'),
  ('CFO', "Loans", 'NONE'),
  ('CFO', "Compliance", 'VIEW'),
  ('CFO', "HR Letters", 'NONE'),
  ('CFO', "Policies", 'VIEW'),
  ('CFO', "Reports", 'VIEW'),
  ('CFO', "ESS & Roles", 'NONE'),
  ('CFO', "Admin Setup", 'NONE'),
  ('CFO', "Company Profile", 'VIEW'),
  ('CFO', "Ezer AI", 'VIEW'),
  ('CFO', "Support", 'VIEW'),
  ('MD', "Recruitment", 'VIEW'),
  ('MD', "Onboarding", 'NONE'),
  ('MD', "Performance", 'VIEW'),
  ('MD', "Employees", 'VIEW'),
  ('MD', "Bulk Upload", 'NONE'),
  ('MD', "Transfer", 'NONE'),
  ('MD', "Attendance", 'NONE'),
  ('MD', "Attendance Reports", 'NONE'),
  ('MD', "Leave Config", 'NONE'),
  ('MD', "Holidays", 'NONE'),
  ('MD', "Payroll", 'VIEW'),
  ('MD', "Finance", 'VIEW'),
  ('MD', "Flexi Claims", 'NONE'),
  ('MD', "Travel Claims", 'VIEW'),
  ('MD', "Loans", 'NONE'),
  ('MD', "Compliance", 'VIEW'),
  ('MD', "HR Letters", 'NONE'),
  ('MD', "Policies", 'VIEW'),
  ('MD', "Reports", 'VIEW'),
  ('MD', "ESS & Roles", 'NONE'),
  ('MD', "Admin Setup", 'NONE'),
  ('MD', "Company Profile", 'VIEW'),
  ('MD', "Ezer AI", 'VIEW'),
  ('MD', "Support", 'VIEW'),
  ('HR_HEAD', "Recruitment", 'VIEW'),
  ('HR_HEAD', "Onboarding", 'VIEW'),
  ('HR_HEAD', "Performance", 'VIEW'),
  ('HR_HEAD', "Employees", 'VIEW'),
  ('HR_HEAD', "Bulk Upload", 'NONE'),
  ('HR_HEAD', "Transfer", 'VIEW'),
  ('HR_HEAD', "Attendance", 'VIEW'),
  ('HR_HEAD', "Attendance Reports", 'VIEW'),
  ('HR_HEAD', "Leave Config", 'VIEW'),
  ('HR_HEAD', "Holidays", 'VIEW'),
  ('HR_HEAD', "Payroll", 'VIEW'),
  ('HR_HEAD', "Finance", 'VIEW'),
  ('HR_HEAD', "Flexi Claims", 'VIEW'),
  ('HR_HEAD', "Travel Claims", 'VIEW'),
  ('HR_HEAD', "Loans", 'NONE'),
  ('HR_HEAD', "Compliance", 'VIEW'),
  ('HR_HEAD', "HR Letters", 'VIEW'),
  ('HR_HEAD', "Policies", 'FULL'),
  ('HR_HEAD', "Reports", 'VIEW'),
  ('HR_HEAD', "ESS & Roles", 'FULL'),
  ('HR_HEAD', "Admin Setup", 'FULL'),
  ('HR_HEAD', "Company Profile", 'FULL'),
  ('HR_HEAD', "Ezer AI", 'VIEW'),
  ('HR_HEAD', "Support", 'VIEW'),
  ('CHRO', "Recruitment", 'VIEW'),
  ('CHRO', "Onboarding", 'VIEW'),
  ('CHRO', "Performance", 'VIEW'),
  ('CHRO', "Employees", 'VIEW'),
  ('CHRO', "Bulk Upload", 'NONE'),
  ('CHRO', "Transfer", 'VIEW'),
  ('CHRO', "Attendance", 'VIEW'),
  ('CHRO', "Attendance Reports", 'VIEW'),
  ('CHRO', "Leave Config", 'VIEW'),
  ('CHRO', "Holidays", 'VIEW'),
  ('CHRO', "Payroll", 'VIEW'),
  ('CHRO', "Finance", 'VIEW'),
  ('CHRO', "Flexi Claims", 'VIEW'),
  ('CHRO', "Travel Claims", 'VIEW'),
  ('CHRO', "Loans", 'NONE'),
  ('CHRO', "Compliance", 'VIEW'),
  ('CHRO', "HR Letters", 'VIEW'),
  ('CHRO', "Policies", 'FULL'),
  ('CHRO', "Reports", 'VIEW'),
  ('CHRO', "ESS & Roles", 'FULL'),
  ('CHRO', "Admin Setup", 'FULL'),
  ('CHRO', "Company Profile", 'FULL'),
  ('CHRO', "Ezer AI", 'VIEW'),
  ('CHRO', "Support", 'VIEW'),
  ('HR_MANAGER', "Recruitment", 'FULL'),
  ('HR_MANAGER', "Onboarding", 'FULL'),
  ('HR_MANAGER', "Performance", 'FULL'),
  ('HR_MANAGER', "Employees", 'FULL'),
  ('HR_MANAGER', "Bulk Upload", 'FULL'),
  ('HR_MANAGER', "Transfer", 'FULL'),
  ('HR_MANAGER', "Attendance", 'FULL'),
  ('HR_MANAGER', "Attendance Reports", 'FULL'),
  ('HR_MANAGER', "Leave Config", 'FULL'),
  ('HR_MANAGER', "Holidays", 'FULL'),
  ('HR_MANAGER', "Payroll", 'NONE'),
  ('HR_MANAGER', "Finance", 'NONE'),
  ('HR_MANAGER', "Flexi Claims", 'VIEW'),
  ('HR_MANAGER', "Travel Claims", 'FULL'),
  ('HR_MANAGER', "Loans", 'VIEW'),
  ('HR_MANAGER', "Compliance", 'VIEW'),
  ('HR_MANAGER', "HR Letters", 'FULL'),
  ('HR_MANAGER', "Policies", 'FULL'),
  ('HR_MANAGER', "Reports", 'EDIT'),
  ('HR_MANAGER', "ESS & Roles", 'FULL'),
  ('HR_MANAGER', "Admin Setup", 'FULL'),
  ('HR_MANAGER', "Company Profile", 'VIEW'),
  ('HR_MANAGER', "Ezer AI", 'VIEW'),
  ('HR_MANAGER', "Support", 'VIEW'),
  ('PAYROLL', "Recruitment", 'NONE'),
  ('PAYROLL', "Onboarding", 'VIEW'),
  ('PAYROLL', "Performance", 'NONE'),
  ('PAYROLL', "Employees", 'FULL'),
  ('PAYROLL', "Bulk Upload", 'FULL'),
  ('PAYROLL', "Transfer", 'NONE'),
  ('PAYROLL', "Attendance", 'FULL'),
  ('PAYROLL', "Attendance Reports", 'FULL'),
  ('PAYROLL', "Leave Config", 'FULL'),
  ('PAYROLL', "Holidays", 'FULL'),
  ('PAYROLL', "Payroll", 'FULL'),
  ('PAYROLL', "Finance", 'VIEW'),
  ('PAYROLL', "Flexi Claims", 'FULL'),
  ('PAYROLL', "Travel Claims", 'NONE'),
  ('PAYROLL', "Loans", 'FULL'),
  ('PAYROLL', "Compliance", 'FULL'),
  ('PAYROLL', "HR Letters", 'VIEW'),
  ('PAYROLL', "Policies", 'VIEW'),
  ('PAYROLL', "Reports", 'FULL'),
  ('PAYROLL', "ESS & Roles", 'NONE'),
  ('PAYROLL', "Admin Setup", 'NONE'),
  ('PAYROLL', "Company Profile", 'VIEW'),
  ('PAYROLL', "Ezer AI", 'VIEW'),
  ('PAYROLL', "Support", 'VIEW'),
  ('PAYROLL_ADMIN', "Recruitment", 'NONE'),
  ('PAYROLL_ADMIN', "Onboarding", 'VIEW'),
  ('PAYROLL_ADMIN', "Performance", 'NONE'),
  ('PAYROLL_ADMIN', "Employees", 'FULL'),
  ('PAYROLL_ADMIN', "Bulk Upload", 'FULL'),
  ('PAYROLL_ADMIN', "Transfer", 'NONE'),
  ('PAYROLL_ADMIN', "Attendance", 'FULL'),
  ('PAYROLL_ADMIN', "Attendance Reports", 'FULL'),
  ('PAYROLL_ADMIN', "Leave Config", 'FULL'),
  ('PAYROLL_ADMIN', "Holidays", 'FULL'),
  ('PAYROLL_ADMIN', "Payroll", 'FULL'),
  ('PAYROLL_ADMIN', "Finance", 'VIEW'),
  ('PAYROLL_ADMIN', "Flexi Claims", 'FULL'),
  ('PAYROLL_ADMIN', "Travel Claims", 'NONE'),
  ('PAYROLL_ADMIN', "Loans", 'FULL'),
  ('PAYROLL_ADMIN', "Compliance", 'FULL'),
  ('PAYROLL_ADMIN', "HR Letters", 'VIEW'),
  ('PAYROLL_ADMIN', "Policies", 'VIEW'),
  ('PAYROLL_ADMIN', "Reports", 'FULL'),
  ('PAYROLL_ADMIN', "ESS & Roles", 'NONE'),
  ('PAYROLL_ADMIN', "Admin Setup", 'NONE'),
  ('PAYROLL_ADMIN', "Company Profile", 'VIEW'),
  ('PAYROLL_ADMIN', "Ezer AI", 'VIEW'),
  ('PAYROLL_ADMIN', "Support", 'VIEW'),
  ('IT', "Recruitment", 'NONE'),
  ('IT', "Onboarding", 'VIEW'),
  ('IT', "Performance", 'NONE'),
  ('IT', "Employees", 'VIEW'),
  ('IT', "Bulk Upload", 'NONE'),
  ('IT', "Transfer", 'NONE'),
  ('IT', "Attendance", 'NONE'),
  ('IT', "Attendance Reports", 'NONE'),
  ('IT', "Leave Config", 'NONE'),
  ('IT', "Holidays", 'NONE'),
  ('IT', "Payroll", 'NONE'),
  ('IT', "Finance", 'NONE'),
  ('IT', "Flexi Claims", 'NONE'),
  ('IT', "Travel Claims", 'NONE'),
  ('IT', "Loans", 'NONE'),
  ('IT', "Compliance", 'NONE'),
  ('IT', "HR Letters", 'NONE'),
  ('IT', "Policies", 'VIEW'),
  ('IT', "Reports", 'VIEW'),
  ('IT', "ESS & Roles", 'FULL'),
  ('IT', "Admin Setup", 'FULL'),
  ('IT', "Company Profile", 'NONE'),
  ('IT', "Ezer AI", 'VIEW'),
  ('IT', "Support", 'VIEW'),
  ('ADMIN_COMPANY', "Recruitment", 'NONE'),
  ('ADMIN_COMPANY', "Onboarding", 'VIEW'),
  ('ADMIN_COMPANY', "Performance", 'NONE'),
  ('ADMIN_COMPANY', "Employees", 'VIEW'),
  ('ADMIN_COMPANY', "Bulk Upload", 'NONE'),
  ('ADMIN_COMPANY', "Transfer", 'NONE'),
  ('ADMIN_COMPANY', "Attendance", 'NONE'),
  ('ADMIN_COMPANY', "Attendance Reports", 'NONE'),
  ('ADMIN_COMPANY', "Leave Config", 'NONE'),
  ('ADMIN_COMPANY', "Holidays", 'NONE'),
  ('ADMIN_COMPANY', "Payroll", 'NONE'),
  ('ADMIN_COMPANY', "Finance", 'NONE'),
  ('ADMIN_COMPANY', "Flexi Claims", 'NONE'),
  ('ADMIN_COMPANY', "Travel Claims", 'FULL'),
  ('ADMIN_COMPANY', "Loans", 'NONE'),
  ('ADMIN_COMPANY', "Compliance", 'NONE'),
  ('ADMIN_COMPANY', "HR Letters", 'NONE'),
  ('ADMIN_COMPANY', "Policies", 'VIEW'),
  ('ADMIN_COMPANY', "Reports", 'NONE'),
  ('ADMIN_COMPANY', "ESS & Roles", 'NONE'),
  ('ADMIN_COMPANY', "Admin Setup", 'NONE'),
  ('ADMIN_COMPANY', "Company Profile", 'NONE'),
  ('ADMIN_COMPANY', "Ezer AI", 'VIEW'),
  ('ADMIN_COMPANY', "Support", 'VIEW'),
  ('L1_MANAGER', "Recruitment", 'EDIT'),
  ('L1_MANAGER', "Onboarding", 'NONE'),
  ('L1_MANAGER', "Performance", 'EDIT'),
  ('L1_MANAGER', "Employees", 'VIEW'),
  ('L1_MANAGER', "Bulk Upload", 'NONE'),
  ('L1_MANAGER', "Transfer", 'EDIT'),
  ('L1_MANAGER', "Attendance", 'VIEW'),
  ('L1_MANAGER', "Attendance Reports", 'VIEW'),
  ('L1_MANAGER', "Leave Config", 'NONE'),
  ('L1_MANAGER', "Holidays", 'VIEW'),
  ('L1_MANAGER', "Payroll", 'NONE'),
  ('L1_MANAGER', "Finance", 'NONE'),
  ('L1_MANAGER', "Flexi Claims", 'NONE'),
  ('L1_MANAGER', "Travel Claims", 'VIEW'),
  ('L1_MANAGER', "Loans", 'VIEW'),
  ('L1_MANAGER', "Compliance", 'NONE'),
  ('L1_MANAGER', "HR Letters", 'NONE'),
  ('L1_MANAGER', "Policies", 'VIEW'),
  ('L1_MANAGER', "Reports", 'VIEW'),
  ('L1_MANAGER', "ESS & Roles", 'NONE'),
  ('L1_MANAGER', "Admin Setup", 'NONE'),
  ('L1_MANAGER', "Company Profile", 'NONE'),
  ('L1_MANAGER', "Ezer AI", 'VIEW'),
  ('L1_MANAGER', "Support", 'VIEW'),
  ('L2_MANAGER', "Recruitment", 'EDIT'),
  ('L2_MANAGER', "Onboarding", 'NONE'),
  ('L2_MANAGER', "Performance", 'EDIT'),
  ('L2_MANAGER', "Employees", 'VIEW'),
  ('L2_MANAGER', "Bulk Upload", 'NONE'),
  ('L2_MANAGER', "Transfer", 'EDIT'),
  ('L2_MANAGER', "Attendance", 'VIEW'),
  ('L2_MANAGER', "Attendance Reports", 'VIEW'),
  ('L2_MANAGER', "Leave Config", 'NONE'),
  ('L2_MANAGER', "Holidays", 'VIEW'),
  ('L2_MANAGER', "Payroll", 'NONE'),
  ('L2_MANAGER', "Finance", 'NONE'),
  ('L2_MANAGER', "Flexi Claims", 'NONE'),
  ('L2_MANAGER', "Travel Claims", 'VIEW'),
  ('L2_MANAGER', "Loans", 'VIEW'),
  ('L2_MANAGER', "Compliance", 'NONE'),
  ('L2_MANAGER', "HR Letters", 'NONE'),
  ('L2_MANAGER', "Policies", 'VIEW'),
  ('L2_MANAGER', "Reports", 'VIEW'),
  ('L2_MANAGER', "ESS & Roles", 'NONE'),
  ('L2_MANAGER', "Admin Setup", 'NONE'),
  ('L2_MANAGER', "Company Profile", 'NONE'),
  ('L2_MANAGER', "Ezer AI", 'VIEW'),
  ('L2_MANAGER', "Support", 'VIEW'),
  ('HOD', "Recruitment", 'EDIT'),
  ('HOD', "Onboarding", 'NONE'),
  ('HOD', "Performance", 'VIEW'),
  ('HOD', "Employees", 'VIEW'),
  ('HOD', "Bulk Upload", 'NONE'),
  ('HOD', "Transfer", 'EDIT'),
  ('HOD', "Attendance", 'VIEW'),
  ('HOD', "Attendance Reports", 'VIEW'),
  ('HOD', "Leave Config", 'NONE'),
  ('HOD', "Holidays", 'VIEW'),
  ('HOD', "Payroll", 'NONE'),
  ('HOD', "Finance", 'NONE'),
  ('HOD', "Flexi Claims", 'NONE'),
  ('HOD', "Travel Claims", 'VIEW'),
  ('HOD', "Loans", 'VIEW'),
  ('HOD', "Compliance", 'NONE'),
  ('HOD', "HR Letters", 'NONE'),
  ('HOD', "Policies", 'VIEW'),
  ('HOD', "Reports", 'VIEW'),
  ('HOD', "ESS & Roles", 'NONE'),
  ('HOD', "Admin Setup", 'NONE'),
  ('HOD', "Company Profile", 'NONE'),
  ('HOD', "Ezer AI", 'VIEW'),
  ('HOD', "Support", 'VIEW'),
  ('RECRUITER', "Recruitment", 'FULL'),
  ('RECRUITER', "Onboarding", 'NONE'),
  ('RECRUITER', "Performance", 'NONE'),
  ('RECRUITER', "Employees", 'NONE'),
  ('RECRUITER', "Bulk Upload", 'NONE'),
  ('RECRUITER', "Transfer", 'NONE'),
  ('RECRUITER', "Attendance", 'NONE'),
  ('RECRUITER', "Attendance Reports", 'NONE'),
  ('RECRUITER', "Leave Config", 'NONE'),
  ('RECRUITER', "Holidays", 'NONE'),
  ('RECRUITER', "Payroll", 'NONE'),
  ('RECRUITER', "Finance", 'NONE'),
  ('RECRUITER', "Flexi Claims", 'NONE'),
  ('RECRUITER', "Travel Claims", 'NONE'),
  ('RECRUITER', "Loans", 'NONE'),
  ('RECRUITER', "Compliance", 'NONE'),
  ('RECRUITER', "HR Letters", 'NONE'),
  ('RECRUITER', "Policies", 'NONE'),
  ('RECRUITER', "Reports", 'NONE'),
  ('RECRUITER', "ESS & Roles", 'NONE'),
  ('RECRUITER', "Admin Setup", 'NONE'),
  ('RECRUITER', "Company Profile", 'NONE'),
  ('RECRUITER', "Ezer AI", 'VIEW'),
  ('RECRUITER', "Support", 'VIEW'),
  ('FINANCE_EXECUTIVE', "Recruitment", 'NONE'),
  ('FINANCE_EXECUTIVE', "Onboarding", 'NONE'),
  ('FINANCE_EXECUTIVE', "Performance", 'NONE'),
  ('FINANCE_EXECUTIVE', "Employees", 'NONE'),
  ('FINANCE_EXECUTIVE', "Bulk Upload", 'NONE'),
  ('FINANCE_EXECUTIVE', "Transfer", 'NONE'),
  ('FINANCE_EXECUTIVE', "Attendance", 'NONE'),
  ('FINANCE_EXECUTIVE', "Attendance Reports", 'NONE'),
  ('FINANCE_EXECUTIVE', "Leave Config", 'NONE'),
  ('FINANCE_EXECUTIVE', "Holidays", 'NONE'),
  ('FINANCE_EXECUTIVE', "Payroll", 'NONE'),
  ('FINANCE_EXECUTIVE', "Finance", 'FULL'),
  ('FINANCE_EXECUTIVE', "Flexi Claims", 'FULL'),
  ('FINANCE_EXECUTIVE', "Travel Claims", 'VIEW'),
  ('FINANCE_EXECUTIVE', "Loans", 'VIEW'),
  ('FINANCE_EXECUTIVE', "Compliance", 'NONE'),
  ('FINANCE_EXECUTIVE', "HR Letters", 'NONE'),
  ('FINANCE_EXECUTIVE', "Policies", 'VIEW'),
  ('FINANCE_EXECUTIVE', "Reports", 'NONE'),
  ('FINANCE_EXECUTIVE', "ESS & Roles", 'NONE'),
  ('FINANCE_EXECUTIVE', "Admin Setup", 'NONE'),
  ('FINANCE_EXECUTIVE', "Company Profile", 'NONE'),
  ('FINANCE_EXECUTIVE', "Ezer AI", 'VIEW'),
  ('FINANCE_EXECUTIVE', "Support", 'VIEW'),
  ('BRANCH_HR', "Recruitment", 'VIEW'),
  ('BRANCH_HR', "Onboarding", 'VIEW'),
  ('BRANCH_HR', "Performance", 'NONE'),
  ('BRANCH_HR', "Employees", 'VIEW'),
  ('BRANCH_HR', "Bulk Upload", 'NONE'),
  ('BRANCH_HR', "Transfer", 'EDIT'),
  ('BRANCH_HR', "Attendance", 'VIEW'),
  ('BRANCH_HR', "Attendance Reports", 'VIEW'),
  ('BRANCH_HR', "Leave Config", 'NONE'),
  ('BRANCH_HR', "Holidays", 'VIEW'),
  ('BRANCH_HR', "Payroll", 'NONE'),
  ('BRANCH_HR', "Finance", 'NONE'),
  ('BRANCH_HR', "Flexi Claims", 'NONE'),
  ('BRANCH_HR', "Travel Claims", 'NONE'),
  ('BRANCH_HR', "Loans", 'NONE'),
  ('BRANCH_HR', "Compliance", 'NONE'),
  ('BRANCH_HR', "HR Letters", 'VIEW'),
  ('BRANCH_HR', "Policies", 'VIEW'),
  ('BRANCH_HR', "Reports", 'VIEW'),
  ('BRANCH_HR', "ESS & Roles", 'VIEW'),
  ('BRANCH_HR', "Admin Setup", 'NONE'),
  ('BRANCH_HR', "Company Profile", 'NONE'),
  ('BRANCH_HR', "Ezer AI", 'VIEW'),
  ('BRANCH_HR', "Support", 'VIEW'),
  ('BRANCH_EXEC', "Recruitment", 'VIEW'),
  ('BRANCH_EXEC', "Onboarding", 'VIEW'),
  ('BRANCH_EXEC', "Performance", 'NONE'),
  ('BRANCH_EXEC', "Employees", 'VIEW'),
  ('BRANCH_EXEC', "Bulk Upload", 'NONE'),
  ('BRANCH_EXEC', "Transfer", 'EDIT'),
  ('BRANCH_EXEC', "Attendance", 'VIEW'),
  ('BRANCH_EXEC', "Attendance Reports", 'VIEW'),
  ('BRANCH_EXEC', "Leave Config", 'NONE'),
  ('BRANCH_EXEC', "Holidays", 'VIEW'),
  ('BRANCH_EXEC', "Payroll", 'NONE'),
  ('BRANCH_EXEC', "Finance", 'NONE'),
  ('BRANCH_EXEC', "Flexi Claims", 'NONE'),
  ('BRANCH_EXEC', "Travel Claims", 'NONE'),
  ('BRANCH_EXEC', "Loans", 'NONE'),
  ('BRANCH_EXEC', "Compliance", 'NONE'),
  ('BRANCH_EXEC', "HR Letters", 'VIEW'),
  ('BRANCH_EXEC', "Policies", 'VIEW'),
  ('BRANCH_EXEC', "Reports", 'VIEW'),
  ('BRANCH_EXEC', "ESS & Roles", 'VIEW'),
  ('BRANCH_EXEC', "Admin Setup", 'NONE'),
  ('BRANCH_EXEC', "Company Profile", 'NONE'),
  ('BRANCH_EXEC', "Ezer AI", 'VIEW'),
  ('BRANCH_EXEC', "Support", 'VIEW'),
  ('EMPLOYEE', "Recruitment", 'NONE'),
  ('EMPLOYEE', "Onboarding", 'NONE'),
  ('EMPLOYEE', "Performance", 'NONE'),
  ('EMPLOYEE', "Employees", 'NONE'),
  ('EMPLOYEE', "Bulk Upload", 'NONE'),
  ('EMPLOYEE', "Transfer", 'NONE'),
  ('EMPLOYEE', "Attendance", 'NONE'),
  ('EMPLOYEE', "Attendance Reports", 'NONE'),
  ('EMPLOYEE', "Leave Config", 'NONE'),
  ('EMPLOYEE', "Holidays", 'NONE'),
  ('EMPLOYEE', "Payroll", 'NONE'),
  ('EMPLOYEE', "Finance", 'NONE'),
  ('EMPLOYEE', "Flexi Claims", 'NONE'),
  ('EMPLOYEE', "Travel Claims", 'NONE'),
  ('EMPLOYEE', "Loans", 'NONE'),
  ('EMPLOYEE', "Compliance", 'NONE'),
  ('EMPLOYEE', "HR Letters", 'NONE'),
  ('EMPLOYEE', "Policies", 'NONE'),
  ('EMPLOYEE', "Reports", 'NONE'),
  ('EMPLOYEE', "ESS & Roles", 'NONE'),
  ('EMPLOYEE', "Admin Setup", 'NONE'),
  ('EMPLOYEE', "Company Profile", 'NONE'),
  ('EMPLOYEE', "Ezer AI", 'NONE'),
  ('EMPLOYEE', "Support", 'NONE')
) as v(role_code, module, access_level)
join public.ess_roles r on r.role_code = v.role_code
on conflict (role_id, module) do update set access_level = excluded.access_level, updated_at = now();
